### ISSUE TITLE
ckanext-oaipmh_repository incompatible ckan versions 2.8

### ISSUE THREAD

**Issue by RandomDev507** [EnviDat/ckanext-oaipmh_repository#1]
I'm trying to run the plugin in Ckan v.2.8, but I get the error like that: No matching distribution found for ckanext-oaipmh_repository. Also, I have tried overwritten my dev-requirements (pytz 2016.4 to 2016.7), but it seems not work.

![c](https://user-images.githubusercontent.com/25469591/41256030-07ab7d6c-6d8e-11e8-8df8-2877f90d5158.jpg)

**Comment by espona** [comment]
I am sorry to tell you but we won't use this extension anymore in our project and we can't work on it to support version 2.8, the repository may go away soon. Also I must tell you that this is a very specific extension and requires the set up of a dedicated Solr node and database, we didn't expect other users to install it. We needed to return resources and datasets and together in batches, quite an uncommon use-case. There are other general-purpose OAIPMH CKAN extensions, properly documented, widely used and much easier to set up. Please take a look at https://github.com/kata-csc/ckanext-oaipmh

**Comment by RandomDev507** [comment]
Thank you very much for the information you have given me and I convey to you best wishes

**Comment by FacundoAdorno** [comment]
Hi!
For any interested, i have modified this plugin for compatibility with CKAN 2.7.3 (check at https://github.com/sedici/ckanext-oaipmh_repository). I have not tested this at 2.8 yet, although this changes could work at this version.
Bye!

**Comment by espona** [comment]
Thanks Facundo but as I said in my comment above we are no longer interested on this extension as it is. We plan to simplify and change it a lot in the next months sonwe can use it for a different purpose. Anyway we appreciate your contribution. Best, Lucia
